name: documentation

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - ingestion-sphinx-docs
  # release:
  #   types: [published, edited]

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Docs
        run: |
          ./gradlew --info docs-website:build
      - name: Deploy
        if: github.event_name == 'push' && github.repository == 'linkedin/datahub'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-website/build
          cname: datahubproject.io

  ingestion-sphinx-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: ./metadata-ingestion/scripts/install_deps.sh
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Docs
        run: |
          ./gradlew --info :metadata-ingestion:makeDocSite
      - name: Deploy
        # if: github.event_name == 'push' && github.repository == 'linkedin/datahub'
        if: github.event_name == 'push' && github.repository == 'kevinhu/datahub'
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: "ingestion-docs"
          commit-message: "Update ingestion docs: ${{ env.DATE }}"
          force-add: "true"
          name: github-actions
          email: github-actions@github.com
        # uses: actions/checkout@v2
        # with:
        #   ref: "ingestion-docs"
        # run: |
        #   git config user.name github-actions
        #   git config user.email github-actions@github.com
        #   git add .
        #   git commit -m "generated"
        #   git push
        # uses: peaceiris/actions-gh-pages@v3
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   publish_dir: ./docs-website/build
        #   cname: datahubproject.io
